### ISSUE TITLE
Amazing library

### ISSUE THREAD

**Issue by Bryce-huang** [LeeEirc/terminalparser#3]
I am looking for a similar library, it seems to work well in my project, thanks
I would like to ask how you learn and process the data returned by the terminal? This has bothered me for a long time

**Comment by LeeEirc** [comment]
I’m glad to be of help to you. 
It is a long story. I have learned a lot  since reading [xterm.js](https://github.com/xtermjs/xterm.js) source code.

**Comment by Bryce-huang** [comment]
Thanks for sharing
